 provinceJson={
				'beijing':'北京市',
				'tianjin':'天津市',
				'hebei':'河北省',
				'guangdong':'广东省',
				'shanghai':'上海市',
				'chongqing':'重庆市',
				'liaoning':'辽宁省',
				'jiangsu':'江苏省',
				'hubei':'湖北省',
				'sichuan':'四川省',
				'shaanxi':'陕西省',
				'shanxi':'山西省',
				'henan':'河南省',
				'jilin':'吉林省',
				'heilongjiang':'黑龙江省',
				'neimenggu':'内蒙古',
				'shandong':'山东省',
				'anhui':'安徽省',
				'zhejiang':'浙江省',
				'fujian':'福建省',
				'hunan':'湖南省',
				'guangxi':'广西省',
				'jiangxi':'江西省',
				'guizhou':'贵州省',
				'yunnan':'云南省',
				'xizang':'西藏省',
				'hainan':'海南省',
				'gansu':'甘肃省',
				'ningxia':'宁夏省',
				'qinghai':'青海省',
				'xinjiang':'新疆省',
				'xianggang':'香港',
				'aomen':'澳门',
				'taiwan':'台湾'
			},
			   

			 

			 

			 

			 


cityJson = 	{
		 	"beijing":[
			{"name":"东城区","value":"dongchengqu"},
			{"name":"西城区","value":"xichengqu"},
			{"name":"崇文区","value":"chongwenqu"},
			{"name":"宣武区","value":"xuanwuqu"},
			{"name":"朝阳区","value":"chaoyangqu"},
			{"name":"海淀区","value":"haidianqu"},
			{"name":"丰台区","value":"fengtaiqu"},
			{"name":"石景山区","value":"shijingshanqu"},
			{"name":"房山区","value":"fangshanqu"},
			{"name":"通州区","value":"tongzhouqu"},
			{"name":"顺义区","value":"shunyiqu"},
			{"name":"昌平区","value":"changpingqu"},
			{"name":"大兴区","value":"daxingqu"},
			{"name":"怀柔区","value":"huairouqu"},
			{"name":"平谷区","value":"pingguqu"},
			{"name":"门头沟区","value":"mentougouqu"},
			{"name":"密云县","value":"miyunxian"},
			{"name":"延庆县","value":"yanqingxian"}],
			"guangdong":[
			{"name":"广州","value":"guangzhou"},
			{"name":"深圳","value":"shenzhen"},
			{"name":"珠海","value":"zhuhai"},
			{"name":"汕头","value":"shantou"},
			{"name":"韶关","value":"shaoguan"},
			{"name":"佛山","value":"foshan"},
			{"name":"江门","value":"jiangmen"},
			{"name":"湛江","value":"zhanjiang"},
			{"name":"茂名","value":"maoming"},
			{"name":"肇庆","value":"zhaoqing"},
			{"name":"惠州","value":"huizhou"},
			{"name":"梅州","value":"meizhou"},
			{"name":"汕尾","value":"shanwei"},
			{"name":"河源","value":"heyuan"},
			{"name":"阳江","value":"yangjiang"},
			{"name":"清远","value":"qingyuan"},
			{"name":"东莞","value":"dongguan"},
			{"name":"中山","value":"zhongshan"},
			{"name":"潮州","value":"chaozhou"},
			{"name":"揭阳","value":"jieyang"},
			{"name":"云浮","value":"yunfu"}],
			"shanghai":[
			{"name":"黄浦区","value":"huangpuqu"},
			{"name":"卢湾区","value":"luhaiqu"},
			{"name":"徐汇区","value":"xuhuiqu"},
			{"name":"长宁区","value":"changningqu"},
			{"name":"静安区","value":"jinganqu"},
			{"name":"普陀区","value":"putuoqu"},
			{"name":"闸北区","value":"zhabeiqu"},
			{"name":"虹口区","value":"hongkouqu"},
			{"name":"杨浦区","value":"yangpuqu"},
			{"name":"宝山区","value":"baoshanqu"},
			{"name":"闵行区","value":"minhangqu"},
			{"name":"嘉定区","value":"jiadingqu"},
			{"name":"松江区","value":"songjiangqu"},
			{"name":"金山区","value":"jinshanqu"},
			{"name":"青浦区","value":"qingpuqu"},
			{"name":"南汇区","value":"nanhuiqu"},
			{"name":"奉贤区","value":"fengxianqu"},
			{"name":"浦东新区","value":"pudongxinqu"},
			{"name":"崇明县","value":"chongmingxian"}],
			"tianjin":[
			{"name":"和平区","value":"hepingqu"},
			{"name":"河东区","value":"hedongqu"},
			{"name":"河西区","value":"hexiqu"},
			{"name":"南开区","value":"nankaiqu"},
			{"name":"河北区","value":"hebeiqu"},
			{"name":"红桥区","value":"hongqiaoqu"},
			{"name":"塘沽区","value":"tangguqu"},
			{"name":"汉沽区","value":"hanguqu"},
			{"name":"大港区","value":"dagangqu"},
			{"name":"东丽区","value":"dongliqu"},
			{"name":"西青区","value":"xiqingqu"},
			{"name":"北辰区","value":"beichenqu"},
			{"name":"津南区","value":"jinnanqu"},
			{"name":"武清区","value":"wuqingqu"},
			{"name":"宝坻区","value":"baodiqu"},
			{"name":"静海县","value":"jinghaixian"},
			{"name":"宁河县","value":"ninghexian"},
			{"name":"蓟县","value":"jixian"}],
			"chongqing":[
			{"name":"渝中区","value":"yuzhongqu"},
			{"name":"大渡口区","value":"dadukouqu"},
			{"name":"江北区","value":"jiangbeiqu"},
			{"name":"南岸区","value":"nananqu"},
			{"name":"北碚区","value":"beibeiqu"},
			{"name":"渝北区","value":"yubeiqu"},
			{"name":"巴南区","value":"bananqu"},
			{"name":"长寿区","value":"changshouqu"},
			{"name":"双桥区","value":"shangqiaoqu"},
			{"name":"沙坪坝区","value":"shapingbaqu"},
			{"name":"万盛区","value":"wanshengqu"},
			{"name":"万州区","value":"wanzhouqu"},
			{"name":"涪陵区","value":"pulingqu"},
			{"name":"黔江区","value":"qianjiangqu"},
			{"name":"永川区","value":"yongchuanqu"},
			{"name":"合川区","value":"hechuangqu"},
			{"name":"江津区","value":"jiangjinqu"},
			{"name":"九龙坡区","value":"jiulongpoqu"},
			{"name":"南川区","value":"nanchuanqu"},
			{"name":"綦江县","value":"qijiangxian"},
			{"name":"潼南县","value":"tongnanxian"},
			{"name":"荣昌县","value":"rongchangxian"},
			{"name":"璧山县","value":"bishanxian"},
			{"name":"大足县","value":"dazuxian"},
			{"name":"铜梁县","value":"tongliangxian"},
			{"name":"梁平县","value":"liangpingxian"},
			{"name":"开县","value":"kaixian"},
			{"name":"忠县","value":"zhongxian"},
			{"name":"城口县","value":"chengkouxian"},
			{"name":"垫江县","value":"dianjiangxian"},
			{"name":"武隆县","value":"wulongxian"},
			{"name":"丰都县","value":"fengduxian"},
			{"name":"奉节县","value":"fengjiexian"},
			{"name":"云阳县","value":"yunyangxian"},
			{"name":"巫溪县","value":"wuxixian"},
			{"name":"巫山县","value":"wushanxian"},
			{"name":"石柱土家族自治县","value":"shizhutujiazuzizhixian"},
			{"name":"秀山土家族苗族自治县","value":"xiushantujiazumianzuzizhixian"},
			{"name":"酉阳土家族苗族自治县","value":"youyangtujiazumianzuzizhixian"},
			{"name":"彭水苗族土家族自治县","value":"pengshuimianzutujiazuzizhixian"}],
			"liaoning":[
			{"name":"沈阳","value":"shenyang"},
			{"name":"大连","value":"dalian"},
			{"name":"鞍山","value":"anshan"},
			{"name":"抚顺","value":"fushun"},
			{"name":"本溪","value":"benxi"},
			{"name":"丹东","value":"dandong"},
			{"name":"锦州","value":"jinzhou"},
			{"name":"营口","value":"yingkou"},
			{"name":"阜新","value":"fuxin"},
			{"name":"辽阳","value":"liaoyang"},
			{"name":"盘锦","value":"panjin"},
			{"name":"铁岭","value":"tieling"},
			{"name":"朝阳","value":"chaoyang"},
			{"name":"葫芦岛","value":"huludao"}],
			"jiangsu":[
			{"name":"南京","value":"nanjing"},
			{"name":"苏州","value":"suzhou"},
			{"name":"无锡","value":"wuxi"},
			{"name":"常州","value":"changzhou"},
			{"name":"镇江","value":"zhenjiang"},
			{"name":"南通","value":"nantong"},
			{"name":"泰州","value":"taizhou"},
			{"name":"扬州","value":"yangzhou"},
			{"name":"盐城","value":"yancheng"},
			{"name":"连云港","value":"lianyungang"},
			{"name":"徐州","value":"xuzhou"},
			{"name":"淮安","value":"huaian"},
			{"name":"宿迁","value":"suqian"}],
			"hubei":[
			{"name":"武汉","value":"wuhan"},
			{"name":"黄石","value":"huangshi"},
			{"name":"十堰","value":"shiyan"},
			{"name":"荆州","value":"jingzhou"},
			{"name":"宜昌","value":"yichang"},
			{"name":"襄樊","value":"xiangfan"},
			{"name":"鄂州","value":"ezhou"},
			{"name":"荆门","value":"jingmen"},
			{"name":"孝感","value":"xiaogan"},
			{"name":"黄冈","value":"huanggang"},
			{"name":"咸宁","value":"xianning"},
			{"name":"随州","value":"suizhou"},
			{"name":"恩施土家族苗族自治州","value":"enshitujiazumiaozuzizhizhou"},
			{"name":"仙桃","value":"xiantao"},
			{"name":"天门","value":"tianmen"},
			{"name":"潜江","value":"qianjiang"},
			{"name":"神农架林区","value":"shennongjialinqu"}],
			"sichuan":[
			{"name":"成都","value":"chengdu"},
			{"name":"自贡","value":"zigong"},
			{"name":"攀枝花","value":"panzhihua"},
			{"name":"泸州","value":"luzhou"},
			{"name":"德阳","value":"deyang"},
			{"name":"绵阳","value":"mianyang"},
			{"name":"广元","value":"guangyuan"},
			{"name":"遂宁","value":"suining"},
			{"name":"内江","value":"neijiang"},
			{"name":"乐山","value":"leshan"},
			{"name":"南充","value":"nanchong"},
			{"name":"眉山","value":"meishan"},
			{"name":"宜宾","value":"yibin"},
			{"name":"广安","value":"guangan"},
			{"name":"达州","value":"dazhou"},
			{"name":"雅安","value":"yaan"},
			{"name":"巴中","value":"bazhong"},
			{"name":"资阳","value":"ziyang"},
			{"name":"阿坝藏族羌族自治州","value":"abazangzuqiangzuzizhizhou"},
			{"name":"甘孜藏族自治州","value":"ganzizangzuzizhizhou"},
			{"name":"凉山彝族自治州","value":"liangshanyizuzizhizhou"}],
			"shaanxi":[
			{"name":"西安","value":"xian"},
			{"name":"铜川","value":"tongchuan"},
			{"name":"宝鸡","value":"baoji"},
			{"name":"咸阳","value":"xianyang"},
			{"name":"渭南","value":"weinan"},
			{"name":"延安","value":"yanan"},
			{"name":"汉中","value":"hanzhong"},
			{"name":"榆林","value":"yulin"},
			{"name":"安康","value":"ankang"},
			{"name":"商洛","value":"shangluo"}],
			"hebei":[
			{"name":"石家庄","value":"shijiazhuang"},
			{"name":"唐山","value":"tangshan"},
			{"name":"秦皇岛","value":"qinhuangdao"},
			{"name":"邯郸","value":"handan"},
			{"name":"邢台","value":"xingtai"},
			{"name":"保定","value":"baoding"},
			{"name":"张家口","value":"zhangjiakou"},
			{"name":"承德","value":"chengde"},
			{"name":"沧州","value":"cangzhou"},
			{"name":"廊坊","value":"langfang"},
			{"name":"衡水","value":"hengshui"}],
			"shanxi":[
			{"name":"太原","value":"taiyuan"},
			{"name":"大同","value":"datong"},
			{"name":"阳泉","value":"yangquan"},
			{"name":"长治","value":"changzhi"},
			{"name":"晋城","value":"jincheng"},
			{"name":"朔州","value":"shuozhou"},
			{"name":"晋中","value":"jinzhong"},
			{"name":"运城","value":"yuncheng"},
			{"name":"忻州","value":"xinzhou"},
			{"name":"临汾","value":"linfen"},
			{"name":"吕梁","value":"lvliang"}],
			"henan":[
			{"name":"郑州","value":"zhengzhou"},
			{"name":"开封","value":"kaifeng"},
			{"name":"洛阳","value":"luoyang"},
			{"name":"平顶山","value":"pingdingshan"},
			{"name":"安阳","value":"anyang"},
			{"name":"鹤壁","value":"hebi"},
			{"name":"新乡","value":"xinxiang"},
			{"name":"焦作","value":"jiaozuo"},
			{"name":"濮阳","value":"puyang"},
			{"name":"许昌","value":"xuchang"},
			{"name":"漯河","value":"luohe"},
			{"name":"三门峡","value":"sanmenxia"},
			{"name":"南阳","value":"nanyang"},
			{"name":"商丘","value":"shangqiu"},
			{"name":"信阳","value":"xinyang"},
			{"name":"周口","value":"zhoukou"},
			{"name":"驻马店","value":"zhumadian"},
			{"name":"焦作","value":"jiaozuo"}],
			"jilin":[
			{"name":"长春","value":"changchun"},
			{"name":"吉林","value":"jilin"},
			{"name":"四平","value":"siping"},
			{"name":"辽源","value":"liaoyuan"},
			{"name":"通化","value":"tonghua"},
			{"name":"白山","value":"baishan"},
			{"name":"松原","value":"songyuan"},
			{"name":"白城","value":"baicheng"},
			{"name":"延边朝鲜族自治州","value":"yanbianchaoxianzuzizhizhou"}],
			"heilongjiang":[
			{"name":"哈尔滨","value":"haerbin"},
			{"name":"齐齐哈尔","value":"qiqihaer"},
			{"name":"鹤岗","value":"hegang"},
			{"name":"双鸭山","value":"shuangyashan"},
			{"name":"鸡西","value":"jixi"},
			{"name":"大庆","value":"daqing"},
			{"name":"伊春","value":"yichun"},
			{"name":"牡丹江","value":"mudanjiang"},
			{"name":"佳木斯","value":"jiamusi"},
			{"name":"七台河","value":"qitaihe"},
			{"name":"黑河","value":"heihe"},
			{"name":"绥化","value":"suihua"},
			{"name":"大兴安岭地区","value":"daxinganlingdiqu"}],
			"neimenggu":[
			{"name":"呼和浩特","value":"huhehaote"},
			{"name":"包头","value":"baotou"},
			{"name":"乌海","value":"wuhai"},
			{"name":"赤峰","value":"chifeng"},
			{"name":"通辽","value":"tongliao"},
			{"name":"鄂尔多斯","value":"eerduosi"},
			{"name":"呼伦贝尔","value":"hulunbeier"},
			{"name":"巴彦淖尔","value":"bayannaoer"},
			{"name":"乌兰察布","value":"wulanchabu"},
			{"name":"锡林郭勒盟","value":"xilinguolemeng"},
			{"name":"兴安盟","value":"xinganmeng"},
			{"name":"阿拉善盟","value":"alashanmeng"}],
			"shandong":[
			{"name":"济南","value":"jinan"},
			{"name":"青岛","value":"qingdao"},
			{"name":"淄博","value":"zibo"},
			{"name":"枣庄","value":"zaozhuang"},
			{"name":"东营","value":"dongying"},
			{"name":"烟台","value":"yantai"},
			{"name":"潍坊","value":"weifang"},
			{"name":"济宁","value":"jining"},
			{"name":"泰安","value":"taian"},
			{"name":"威海","value":"weihai"},
			{"name":"日照","value":"rizhao"},
			{"name":"莱芜","value":"laiwu"},
			{"name":"临沂","value":"linyi"},
			{"name":"德州","value":"dezhou"},
			{"name":"聊城","value":"liaocheng"},
			{"name":"滨州","value":"binzhou"},
			{"name":"菏泽","value":"heze"}],
			"anhui":[
			{"name":"合肥","value":"hefei"},
			{"name":"芜湖","value":"wuhu"},
			{"name":"蚌埠","value":"bangbu"},
			{"name":"淮南","value":"huainan"},
			{"name":"马鞍山","value":"maanshan"},
			{"name":"淮北","value":"huaibei"},
			{"name":"铜陵","value":"tongling"},
			{"name":"安庆","value":"anqing"},
			{"name":"黄山","value":"huangshan"},
			{"name":"滁州","value":"chuzhou"},
			{"name":"阜阳","value":"fuyang"},
			{"name":"宿州","value":"suzhou"},
			{"name":"巢湖","value":"chaohu"},
			{"name":"六安","value":"liuan"},
			{"name":"亳州","value":"bozhou"},
			{"name":"池州","value":"chizhou"},
			{"name":"宣城","value":"xuancheng"}],
			"zhejiang":[
			{"name":"杭州","value":"hangzhou"},
			{"name":"宁波","value":"ningbo"},
			{"name":"温州","value":"wenzhou"},
			{"name":"嘉兴","value":"jiaxing"},
			{"name":"湖州","value":"huzhou"},
			{"name":"绍兴","value":"shaoxing"},
			{"name":"金华","value":"jinhua"},
			{"name":"衢州","value":"quzhou"},
			{"name":"舟山","value":"zhoushan"},
			{"name":"台州","value":"taizhou"},
			{"name":"丽水","value":"lishui"}],
			"fujian":[
			{"name":"福州","value":"fuzhou"},
			{"name":"厦门","value":"xiamen"},
			{"name":"莆田","value":"putian"},
			{"name":"三明","value":"sanming"},
			{"name":"泉州","value":"quanzhou"},
			{"name":"漳州","value":"zhangzhou"},
			{"name":"南平","value":"nanping"},
			{"name":"龙岩","value":"longyan"},
			{"name":"宁德","value":"ningde"}],
			"hunan":[
			{"name":"长沙","value":"changsha"},
			{"name":"株洲","value":"zhuzhou"},
			{"name":"湘潭","value":"xiangtan"},
			{"name":"衡阳","value":"hengyang"},
			{"name":"邵阳","value":"shaoyang"},
			{"name":"岳阳","value":"yueyang"},
			{"name":"常德","value":"changde"},
			{"name":"张家界","value":"zhangjiajie"},
			{"name":"益阳","value":"yiyang"},
			{"name":"郴州","value":"chenzhou"},
			{"name":"永州","value":"yongzhou"},
			{"name":"怀化","value":"huaihua"},
			{"name":"娄底","value":"loudi"},
			{"name":"湘西土家族苗族自治州","value":"xiangxitujiazumiaozuzizhizhou"}],
			"guangxi":[
			{"name":"南宁","value":"nanning"},
			{"name":"柳州","value":"liuzhou"},
			{"name":"桂林","value":"guilin"},
			{"name":"梧州","value":"wuzhou"},
			{"name":"北海","value":"beihai"},
			{"name":"防城港","value":"fangchenggang"},
			{"name":"钦州","value":"qinzhou"},
			{"name":"贵港","value":"guigang"},
			{"name":"玉林","value":"yulin"},
			{"name":"百色","value":"baise"},
			{"name":"贺州","value":"hezhou"},
			{"name":"河池","value":"hechi"},
			{"name":"来宾","value":"laibin"},
			{"name":"崇左","value":"chongzuo"}],
			"jiangxi":[
			{"name":"南昌","value":"nanchang"},
			{"name":"景德镇","value":"jingdezhen"},
			{"name":"萍乡","value":"pingxiang"},
			{"name":"九江","value":"jiujiang"},
			{"name":"新余","value":"xinyu"},
			{"name":"鹰潭","value":"yingtan"},
			{"name":"赣州","value":"ganzhou"},
			{"name":"吉安","value":"jian"},
			{"name":"宜春","value":"yichun"},
			{"name":"抚州","value":"fuzhou"},
			{"name":"上饶","value":"shangrao"}],
			"guizhou":[
			{"name":"贵阳","value":"guiyang"},
			{"name":"六盘水","value":"liupanshui"},
			{"name":"遵义","value":"zunyi"},
			{"name":"安顺","value":"anshun"},
			{"name":"铜仁地区","value":"tongrendiqu"},
			{"name":"毕节地区","value":"bijiediqu"},
			{"name":"黔西南布依族苗族自治州","value":"qianxinanbuyizumiaozuzizhizhou"},
			{"name":"黔东南苗族侗族自治州","value":"qiandongnanmiaozudongzuzizhizhou"},
			{"name":"黔南布依族苗族自治州","value":"qiannanbuyizumiaozuzizhizhou"}],
			"yunnan":[
			{"name":"昆明","value":"kunming"},
			{"name":"曲靖","value":"qujing"},
			{"name":"玉溪","value":"yuxi"},
			{"name":"保山","value":"baoshan"},
			{"name":"昭通","value":"zhaotong"},
			{"name":"丽江","value":"lijiang"},
			{"name":"普洱","value":"puer"},
			{"name":"临沧","value":"lincang"},
			{"name":"德宏傣族景颇族自治州","value":"dehongdaizujingpozuzizhizhou"},
			{"name":"怒江傈僳族自治州","value":"nujianglisuzuzizhizhou"},
			{"name":"迪庆藏族自治州","value":"diqingzangzuzizhizhou"},
			{"name":"大理白族自治州","value":"dalibaizuzizhizhou"},
			{"name":"楚雄彝族自治州","value":"chuxiongyizuzizhizhou"},
			{"name":"红河哈尼族彝族自治州","value":"honghehanizuyizuzizhizhou"},
			{"name":"文山壮族苗族自治州","value":"wenshanzhuangzumiaozuzizhizhou"},
			{"name":"西双版纳傣族自治州","value":"xishuangbannadaizuzizhizhou"}],
			"xizang":[
			{"name":"拉萨","value":"lasa"},
			{"name":"那曲地区","value":"naqudiqu"},
			{"name":"昌都地区","value":"changdudiqu"},
			{"name":"林芝地区","value":"linzhidiqu"},
			{"name":"山南地区","value":"shannandiqu"},
			{"name":"日喀则地区","value":"rikazediqu"},
			{"name":"阿里地区","value":"alidiqu"}],
			"hainan":[
			{"name":"海口","value":"haikou"},
			{"name":"三亚","value":"sanya"},
			{"name":"五指山","value":"wuzhishan"},
			{"name":"琼海","value":"qionghai"},
			{"name":"儋州","value":"danzhou"},
			{"name":"文昌","value":"wenchang"},
			{"name":"万宁","value":"wanning"},
			{"name":"东方","value":"dongfang"},
			{"name":"澄迈县","value":"chengmaixian"},
			{"name":"定安县","value":"dinganxian"},
			{"name":"屯昌县","value":"tunchangxian"},
			{"name":"临高县","value":"linlixian"},
			{"name":"白沙黎族自治县","value":"baishalizuzizhixian"},
			{"name":"昌江黎族自治县","value":"changjianglizuzizhixian"},
			{"name":"乐东黎族自治县","value":"ledonglizuzizhixian"},
			{"name":"陵水黎族自治县","value":"lingshuilizuzizhixian"},
			{"name":"保亭黎族苗族自治县","value":"baotinglizumiaozuzizhixian"},
			{"name":"琼中黎族苗族自治县","value":"qiongzhonglizumiaozuzizhixian"}],
			"gansu":[
			{"name":"兰州","value":"lanzhou"},
			{"name":"嘉峪关","value":"jiayuguan"},
			{"name":"金昌","value":"jinchang"},
			{"name":"白银","value":"baiyin"},
			{"name":"天水","value":"tianshui"},
			{"name":"武威","value":"wuwei"},
			{"name":"酒泉","value":"jiuquan"},
			{"name":"张掖","value":"zhangye"},
			{"name":"庆阳","value":"qingyang"},
			{"name":"平凉","value":"pingliang"},
			{"name":"定西","value":"dingxi"},
			{"name":"陇南","value":"longnan"},
			{"name":"临夏回族自治州","value":"linxiahuizuzizhizhou"},
			{"name":"甘南藏族自治州","value":"gannanzangzuzizhizhou"}],
			"ningxia":[
			{"name":"银川","value":"yinchuan"},
			{"name":"石嘴山","value":"shizuishan"},
			{"name":"吴忠","value":"wuzhong"},
			{"name":"固原","value":"guyuan"},
			{"name":"中卫","value":"zhongwei"}],
			"qinghai":[
			{"name":"西宁","value":"xining"},
			{"name":"海东地区","value":"haidongdiqu"},
			{"name":"海北藏族自治州","value":"haibeizangzuzizhizhou"},
			{"name":"海南藏族自治州","value":"hainanzangzuzizhizhou"},
			{"name":"黄南藏族自治州","value":"huangnanzangzuzizhizhou"},
			{"name":"果洛藏族自治州","value":"guoluozangzuzizhizhou"},
			{"name":"玉树藏族自治州","value":"yushuzangzuzizhizhou"},
			{"name":"海西蒙古族藏族自治州","value":"haiximengguzuzangzuzizhizhou"}],
			"xinjiang":[
			{"name":"乌鲁木齐","value":"wulumuqi"},
			{"name":"克拉玛依","value":"kelamayi"},
			{"name":"吐鲁番地区","value":"tulufandiqu"},
			{"name":"哈密地区","value":"hamidiqu"},
			{"name":"和田地区","value":"hetiandiqu"},
			{"name":"阿克苏地区","value":"akesudiqu"},
			{"name":"喀什地区","value":"kashidiqu"},
			{"name":"克孜勒苏柯尔克孜自治州","value":"kezilesukeerkezizizhizhou"},
			{"name":"巴音郭楞蒙古自治州","value":"bayinguolengmengguzizhizhou"},
			{"name":"昌吉回族自治州","value":"changjihuizuzizhizhou"},
			{"name":"博尔塔拉蒙古自治州","value":"boertalamengguzizhizhou"},
			{"name":"石河子","value":"shihezi"},
			{"name":"阿拉尔","value":"alaer"},
			{"name":"图木舒克","value":"tumushuke"},
			{"name":"五家渠","value":"wujiaqu"},
			{"name":"伊犁哈萨克自治州","value":"yilihasakezizhizhou"}],
			"xianggang":[
			{"name":"中西区","value":"zhongxiqu"},
			{"name":"湾仔区","value":"wanzaiqu"},
			{"name":"东区","value":"dongqu"},
			{"name":"南区","value":"nanqu"},
			{"name":"深水埗区","value":"shenshuibuqu"},
			{"name":"油尖旺区","value":"youjianwangqu"},
			{"name":"九龙城区","value":"jiulongchengqu"},
			{"name":"黄大仙区","value":"huangdaxianqu"},
			{"name":"观塘区","value":"guantangqu"},
			{"name":"北区","value":"beiqu"},
			{"name":"大埔区","value":"dabuqu"},
			{"name":"沙田区","value":"shatianqu"},
			{"name":"西贡区","value":"xigongqu"},
			{"name":"元朗区","value":"yuanlangqu"},
			{"name":"屯门区","value":"tunmenqu"},
			{"name":"荃湾区","value":"quanwanqu"},
			{"name":"葵青区","value":"kuiqingqu"},
			{"name":"离岛区","value":"lidaoqu"}],
			"aomen":[
			{"name":"花地玛堂区","value":"huadimatangqu"},
			{"name":"圣安多尼堂区","value":"shenganduonitangqu"},
			{"name":"大堂区","value":"datangqu"},
			{"name":"望德堂区","value":"wangdetangqu"},
			{"name":"风顺堂区","value":"fengshuntangqu"},
			{"name":"嘉模堂区","value":"jiamotangqu"},
			{"name":"圣方济各堂区","value":"shengfangjigetangqu"},
			{"name":"路凼","value":"ludangqu"}],
			"taiwan":[
			{"name":"台北市","value":"taibeishi"},
			{"name":"高雄市","value":"gaoxiongshi"},
			{"name":"台北县","value":"taibeixian"},
			{"name":"桃园县","value":"taoyuanxian"},
			{"name":"新竹县","value":"xinzhuxian"},
			{"name":"苗栗县","value":"miaolixian"},
			{"name":"台中县","value":"taizhongxian"},
			{"name":"彰化县","value":"zhanghuaxian"},
			{"name":"南投县","value":"nantouxian"},
			{"name":"云林县","value":"yunlinxian"},
			{"name":"嘉义县","value":"jiayixian"},
			{"name":"台南县","value":"tainanxian"},
			{"name":"高雄县","value":"gaoxiongxian"},
			{"name":"屏东县","value":"pingdongxian"},
			{"name":"宜兰县","value":"yilanxian"},
			{"name":"花莲县","value":"hualianxian"},
			{"name":"台东县","value":"taidongxian"},
			{"name":"澎湖县","value":"penghuxian"},
			{"name":"基隆市","value":"jilongshi"},
			{"name":"新竹市","value":"xinzhushi"},
			{"name":"台中市","value":"taizhongshi"},
			{"name":"嘉义市","value":"jiayishi"},
			{"name":"台南市","value":"tainanshi"}]}


			/*cityJson={
					
					'beijing':[
						{'name':'东城区', 'value':'dongchengqu'},
						{'name':'西城区', 'value':'xichengqu'},
						{'name':'朝阳区', 'value':'chaoyangqu'},
						{'name':'丰台区', 'value':'fengtaiqu'},
						{'name':'石景山区', 'value':'shijingshanqu'},
						{'name':'海淀区', 'value':'haidianqu'},
						{'name':'通州区', 'value':'tongzhouqu'},
						{'name':'顺义区', 'value':'shunyiqu'},
						{'name':'房山区', 'value':'fangshanqu'},
						{'name':'大兴区', 'value':'daxingqu'},
						{'name':'昌平区', 'value':'changpingqu'},
						{'name':'怀柔区', 'value':'huairouqu'},
						{'name':'平谷区', 'value':'pingguqu'},
						{'name':'门头沟区', 'value':'mentougouqu'},
						{'name':'密云区', 'value':'miyunqu'},
						{'name':'延庆区', 'value':'yanqingqu'},
						
					],
					'tianjin':[
								{'name':'和平区', 'value':'hepingqu'},
								{'name':'河东区', 'value':'hedongqu'},
								{'name':'河西区', 'value':'hexiqu'},
								{'name':'南开区', 'value':'nankaiqu'},
								{'name':'河北区', 'value':'hebeiqu'},
								{'name':'红桥区', 'value':'hongqiaoqu'},
								{'name':'滨海新区', 'value':'binhaixinqu'},
								{'name':'东丽区', 'value':'dongliqu'},
								{'name':'西青区', 'value':'xiqingqu'},
								{'name':'津南区', 'value':'jinnanqu'},
								{'name':'北辰区', 'value':'beichenqu'},
								{'name':'武清区', 'value':'wuqingqu'},
								{'name':'宝坻区', 'value':'baodiqu'},
								{'name':'宁河区', 'value':'ninghequ'},
								{'name':'静海区', 'value':'jinghaiqu'},
								{'name':'蓟县', 'value':'jixian'},	
							],
					'heibei':[
								{'name':'石家庄市', 'value':'shijiazhuang'},
								{'name':'唐山市', 'value':'tangshan'},
								{'name':'秦皇岛市', 'value':'qinhuangdao'},
								{'name':'邯郸市','value':'handan'},
								{'name':'承德市', 'value':'chengde'}, 
								{'name':'张家口市', 'value':'zhangjiakou'},
								{'name':'廊坊市', 'value':'langfang'},
								{'name':'衡水市', 'value':'hengshui'},
								{'name':'邢台市', 'value':'xingtai'},
								{'name':'保定市', 'value':'baoding'},
								{'name':'沧州市', 'value':'cangzhou'}
							],	
					
					
				}*/
 
 
 
 
 
 
				